version: "3.7"
services:
  zeta_job_server:
    build:
      context: ""
      dockerfile: Dockerfile
      args:
        - JAR_FILE_NAME=zeta-job-server.jar
        - SPRING_ENV=docker
    image: zeta_job_server:latest
    container_name: zeta_job_server
    restart: always
    volumes:
      - ./logs/:/root/product/data
    ports:
      - "8090:8090" # 格式 "服务器端口:容器端口"
